# Generated by Django 2.2.3 on 2019-07-30 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assetId',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskToBePerformedBy',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timeOfAllocation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workerId',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='hey', max_length=400),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AllocateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfAllocation', models.DateTimeField(default=django.utils.timezone.now)),
                ('taskToBePerformedBy', models.DateTimeField(default=django.utils.timezone.now)),
                ('assetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_Task', to='hotel.Asset')),
                ('taskId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_Task', to='hotel.Asset')),
                ('workerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_of_task', to='hotel.Worker')),
            ],
        ),
    ]
