# Generated by Django 2.2.3 on 2019-07-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20190730_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatetask',
            name='taskId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_Task', to='hotel.Task'),
        ),
    ]
